development:
  adapter: postgresql
  database: exercises_development
  pool: 5
  username: metzbr1
  host: localhost 
 
test:
  adapter: postgresql
  database: exercises_test
  pool: 5
  username: metzbr1
  host:  localhost
 
production:
  adapter: postgresql
  encoding: utf8
  database: exercises
  username: bmetzger
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: exercises.cctul6uu1y0k.us-west-2.rds.amazonaws.com
  port: 5432